apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppap-be
  labels:
    app: ppap-be
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ppap-be
  template:
    metadata:
      labels:
        app: ppap-be
    spec:
      containers:
        - name: ppap-be
          image: "{{ .Values.image.be.repository }}:{{ .Values.image.be.tag }}"
          imagePullPolicy: {{ .Values.image.be.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.be.targetPort }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.database.url }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.database.username }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "{{ .Values.database.driver }}"
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: JWT_REFRESH_SECRET
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
