apiVersion: v1
kind: Service
metadata:
  name: ppap-be-service
spec:
  selector:
    app: ppap-be
  ports:
    - protocol: TCP
      port: {{ .Values.service.be.port }}
      targetPort: 8080
  type: {{ .Values.service.be.type }}
