apiVersion: v1
kind: Service
metadata:
  name: ppap-fe-service
spec:
  selector:
    app: ppap-fe
  ports:
    - protocol: TCP
      port: {{ .Values.service.fe.port }}
      targetPort: 80
  type: {{ .Values.service.fe.type }}
