apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels: {{ include "ppap.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_ACCESS_SECRET: {{ .Values.secret.data.JWT_ACCESS_SECRET | b64enc }}
  JWT_REFRESH_SECRET: {{ .Values.secret.data.JWT_REFRESH_SECRET | b64enc }}
