apiVersion: v1
kind: Service
metadata:
  name: ppap-llm-service
spec:
  selector:
    app: ppap-llm
  ports:
    - protocol: TCP
      port: {{ .Values.service.llm.port }}
      targetPort: 8000
  type: {{ .Values.service.llm.type }}
