apiVersion: v1
kind: Service
metadata:
  name: ppap-mysql-service
spec:
  selector:
    app: ppap-mysql
  ports:
    - protocol: TCP
      port: {{ .Values.service.mysql.port }} # values.yaml에서 설정한 MySQL 포트
      targetPort: {{ .Values.service.mysql.port }} # MySQL 서비스의 targetPort
  type: {{ .Values.service.mysql.type }} # 서비스 타입 (예: ClusterIP)
